export const DANH_SACH_TEP_RIENG_TU_REQUEST = "DANH_SACH_TEP_RIENG_TU_REQUEST";
export const DANH_SACH_TEP_RIENG_TU_SUCCESS = "DANH_SACH_TEP_RIENG_TU_SUCCESS";
export const DANH_SACH_TEP_RIENG_TU_ERROR = "DANH_SACH_TEP_RIENG_TU_ERROR";
