export const DANH_SACH_HIS_DOC_VIDEO_REQUEST =
  "DANH_SACH_HIS_DOC_VIDEO_REQUEST";
export const DANH_SACH_HIS_DOC_VIDEO_SUCCESS =
  "DANH_SACH_HIS_DOC_VIDEO_SUCCESS";
export const DANH_SACH_HIS_DOC_VIDEO_ERROR = "DANH_SACH_HIS_DOC_VIDEO_ERROR";
